### ISSUE TITLE
I don't get how to insert mentions in the example

### ISSUE THREAD

**Issue by jducro** [quartzy/prosemirror-suggestions#10]
Hey! Thank you for your plugin, I tried to run the example and I see the existing mention but I can't get to insert the new one using the @ symbol, could you expand the example a bit so that I can understand on how to start build on your plugin ?
Thanks a lot.

**Comment by tristanpemble** [comment]
hi @jducro – apologies for the late response, I just arrived back from vacation :)

this plugin, and consequentially, the example, will not render any UI. the example should be writing to the browser console with `console.log()`. you can see how it is setup here:

```js
  return [
    suggestionsPlugin({
      debug: true,
      matcher: triggerCharacter('@', { allowSpaces: true }),
      onEnter(args) {
        console.log('start', args);
      },
      onChange(args) {
        console.log('change', args);
      },
      onExit(args) {
        console.log('stop', args);
      },
      onKeyDown({ view, event }) {
        // console.log(event.key);
        return false;
      },
    }),
    ...exampleSetup({ schema }),
  ];
```

let me know if you have any other questions!
