### ISSUE TITLE
Remove Mentions by characters 

### ISSUE THREAD

**Issue by starostin** [quartzy/prosemirror-suggestions#7]
Hello.
First of all I want thank you for your work!
I use the tags and mentions and they work fine.
But I have just one question: for now when I click backspace - the whole mention removes (so it removes completely but not just one character). Could you please share what I do wrong and if it's possible to delete just 1 character from mention by taping backspace?

**Comment by tristanpemble** [comment]
Ah. I believe this was an oversight in how we built it for the mentions/tags use case. The way this was built, I don't believe there is any way to edit the individual characters once the completion has been done. I'm open to pull requests to support this functionality!
